#version 450

#include "lib/nbodycommon.comp"

void main() {
    uint index = gl_GlobalInvocationID.x;
    if (index >= ubo.particleCount) return;

    vec4 pos = particles[index].pos;
    vec3 acc = vec3(0.0);

    for (uint i = 0; i < ubo.particleCount; ++i) {
        applyForce(pos, particles[i].pos, acc);
    }

    particles[index].vel.xyz += ubo.delta * acc;

    // Gradually shift the hue of the particle
    shiftColor(particles[index].vel.w);
}

